### ISSUE TITLE
torch_ scatter==1.3.1 installation was unsuccessful and torch_scatter==2.0.9 have a exception

### ISSUE THREAD

**Issue by yingjun-skr** [harvardnlp/botnet-detection#18]
![image](https://user-images.githubusercontent.com/67632310/164878778-2d98595f-4aef-494d-ad88-d42299975f52.png)

**Comment by yingjun-skr** [comment]
Using GCN model to delete fillvalue can train normally, but with the attention mechanism, it will be abnormal

**Comment by jzhou316** [comment]
Hi there, I believe it is because of the following package incompatibility:
- The [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter/tree/1.4.0) has made some changes of the number of arguments in the above function starting the 2.x versions. But the code was written in version 1.3.1
- The older versions of torch-scatter are not compatible with later PyTorch versions

You can check my previous environment [here](https://github.com/harvardnlp/botnet-detection/issues/8#issuecomment-871847903), to consider downgrading the PyTorch version to install the pytoch_scatter 1.3.1.
Or, you could work with pytorch_scatter 2.0.9, but remove the `fill_value` argument since it is not compatible.

Let me know if any of these work.

**Comment by yingjun-skr** [comment]
Thank you very much for your reply. I have solved this problem and deleted common.py fill_value, and then in the graph_ attention.py deleted scatter_,  Reintroduce scatter_ in common, The program has been able to run normally.
![image](https://user-images.githubusercontent.com/67632310/165111334-eb357793-0079-4ad1-adb1-e467191d1e4a.png)
![image](https://user-images.githubusercontent.com/67632310/165111333-6f8323c2-a10f-4a3d-8135-a2cba809f69c.png)
I have another question 
1e-16 need to delete ？？？
![image](https://user-images.githubusercontent.com/67632310/165111418-7a16fdc8-1cfa-436f-890b-e6e927360d7d.png)

**Comment by jzhou316** [comment]
Sounds great! The small `fill_value` was needed in previous version of torch_scatter for the attention, but it is removed so I wonder if they have fixed it so that we don't need to manage it manually.

**Comment by jzhou316** [comment]
Sure. The original traffic is downloaded from here https://mcfp.weebly.com/the-ctu-13-dataset-a-labeled-dataset-with-botnet-normal-and-background-traffic.html
